DZ04 add a skeleton
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #10
Opened 2024-11-20 21:10 UTC by gamedevshrimp

2024-11-20 21:11 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-20 21:18 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-21 05:02 UTC, GSemikozov requested changes

2024-11-21 05:02 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div class="skeleton__block" style="width: 35%"></div>
тут ширину не стоит инлайнить, у нас всего 3 варианта, поэтому можно через модификаторы

2024-11-21 15:31 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-21 16:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-11-21 18:50 UTC, GSemikozov approved these changes

2024-11-21 18:50 UTC, merged