DZ05 add a modal draft
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #13
Opened 2024-11-28 19:56 UTC by gamedevshrimp

2024-11-28 19:57 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-28 20:17 UTC, GSemikozov requested changes

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal {
.modal

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: auto;
лишнее

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    font-family: 'Inter', sans-serif;
думаю нет смысла

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    line-height: 24px;
и это

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    line-height: 24px;
можно на уровне window

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__fade {
лишний элемент - можно сразу на уровне класса блока

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 40px;
лишнее, надо спозиционировать абсолютом

2024-11-28 20:17 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +                <svg class="modal__close-icon">
иконку завернуть в button

2024-11-29 22:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-30 19:22 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-06 10:22 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +#modal {
добавил и то и то :)

2024-12-06 10:22 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +    margin: auto;
Убрал 🫡

2024-12-06 10:22 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +    font-family: 'Inter', sans-serif;
убрал

2024-12-06 10:22 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +    line-height: 24px;
добавил напрямую в заголовок и текст

2024-12-06 10:22 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +.modal__fade {
да, так и сделал спасибо

2024-12-06 10:33 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +    margin: 40px;
Убрал

2024-12-06 10:33 UTC, gamedevshrimp commented on 05-lection3/02-modal/index.html
> +                <svg class="modal__close-icon">
Завернул

2024-12-12 15:07 UTC, GSemikozov requested changes

2024-12-12 15:07 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal {
здесь речь идет о том, что стилизуем через классы, не нужно через модификатор

2024-12-12 15:07 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    min-height: 294px;
с высотой этот трюк не нужен)

2024-12-12 15:51 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +    min-height: 294px;
Убрал, спасибо

2024-12-12 15:51 UTC, gamedevshrimp commented on 05-lection3/02-modal/modal.css
> +#modal {
Поправил

2024-12-16 20:39 UTC, GSemikozov approved these changes

2024-12-16 20:39 UTC, merged