DZ05 Add a tooltip
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #14
Opened 2024-12-01 10:34 UTC by gamedevshrimp

2024-12-01 10:34 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-03 12:58 UTC, GSemikozov requested changes

2024-12-03 12:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: auto;
это лишнее

2024-12-03 12:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    border-top-color: #4263EB;;
лишняя `;` :)

2024-12-04 15:34 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-04 15:52 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-12-04 15:53 UTC, gamedevshrimp commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: auto;
убрал

2024-12-04 15:53 UTC, gamedevshrimp commented on 05-lection3/01-tooltip/tooltip.css
> +    border-top-color: #4263EB;;
Поправил, спасибо

2024-12-04 22:53 UTC, GSemikozov approved these changes

2024-12-04 22:54 UTC, merged