Add base setup of index.html
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #3
Opened 2024-11-13 22:24 UTC by gamedevshrimp

2024-11-13 22:25 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-14 13:00 UTC, GSemikozov requested changes

2024-11-14 13:00 UTC, GSemikozov commented on assets/css/main.css
> +    width: 1440px;
это лишнее

2024-11-14 13:00 UTC, GSemikozov commented on components/footer/footer.css
> +    width: 640px;
max-width

2024-11-14 13:00 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 96px;
высоту фиксировать не надо (она зависит от вложенного контента)

2024-11-14 13:00 UTC, GSemikozov commented on components/header/header.css
> +    padding-left: 160px;
лишнее

2024-11-14 13:00 UTC, GSemikozov commented on components/header/header.css
> +    padding-top: 96px;
а снизу - не нужно?)

2024-11-14 13:00 UTC, GSemikozov commented on index.html
> +        <page>
`<div class="page">`?

2024-11-14 13:00 UTC, GSemikozov commented on index.html
> +            <header>
<header class="header">

2024-11-14 13:00 UTC, GSemikozov commented on index.html
> +            <footer>
`<footer class="footer">`

2024-11-15 11:24 UTC, GSemikozov approved these changes

2024-11-15 11:24 UTC, merged