Dz03 add primary btn
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #5
Opened 2024-11-14 08:56 UTC by gamedevshrimp

2024-11-14 08:56 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-14 13:03 UTC, GSemikozov requested changes

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +button {
.button

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину не ограничиваем

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
зато не хватает паддингов

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
.button_primary и ниже

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
лучше pointer-events: none

2024-11-14 13:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +}
а еще ведь надо secondary + outline

2024-11-17 13:15 UTC, GSemikozov requested changes

2024-11-17 13:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    text-align: center;
паддинги по-прежнему не заданы

2024-11-17 13:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary {
все еще актуально

2024-11-17 13:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary:disabled {
disabled будет общий, .button:disabled (только полупрозрачность + pointer-events: none)

2024-11-17 13:15 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="button button__primary">Primary</button>
в разметке должны быть кнопки с disabled

2024-11-17 13:15 UTC, GSemikozov commented on assets/css/main.css
> +    width: 1440px;
лишнее

2024-11-19 07:19 UTC, closed without merging