DZ03 add a button
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #8
Opened 2024-11-18 15:23 UTC by gamedevshrimp

2024-11-18 15:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-18 20:32 UTC, GSemikozov requested changes

2024-11-18 20:32 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
не хватает font-family

2024-11-18 20:32 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
лишнее

2024-11-18 20:32 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
лишнее

2024-11-18 20:32 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
лишнее

2024-11-18 20:32 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_alternate:disabled {
тоже лишнее, можно убрать

2024-11-19 06:47 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-19 06:48 UTC, gamedevshrimp commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
добавил

2024-11-19 06:48 UTC, gamedevshrimp commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
убрал

2024-11-19 06:49 UTC, gamedevshrimp commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
убрал

2024-11-19 06:49 UTC, gamedevshrimp commented on 03-lection1/01-button/button.css
> +    opacity: 100%;
убрал

2024-11-19 06:50 UTC, gamedevshrimp commented on 03-lection1/01-button/button.css
> +.button_alternate:disabled {
тоже убрал, правда у этого состояния прозрачность отличалась 30% вместо 50%

2024-11-19 07:17 UTC, GSemikozov approved these changes

2024-11-19 07:17 UTC, merged