DZ04 add a histogram
js-tasks-ru/htmlcss-20241107_gamedevshrimp pull request #9
Opened 2024-11-20 18:03 UTC by gamedevshrimp

2024-11-20 18:03 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-21 04:58 UTC, GSemikozov requested changes

2024-11-21 04:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
лишнее ограничение

2024-11-21 04:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0;
а тогда надо обнулять марджины и паддинги?

2024-11-21 04:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
и еще - height: 50px

2024-11-21 04:58 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <p class="histogram__viewtext">View all</p>
это ссылка `<a>`

2024-11-21 19:36 UTC, gamedevshrimp commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
убрал

2024-11-21 19:36 UTC, gamedevshrimp commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0;
поправил :)

2024-11-21 19:36 UTC, gamedevshrimp commented on 04-lection2/01-histogram/histogram.css
> +    gap: 1px;
сделал, но не нашел этой цифры в макете

2024-11-21 19:37 UTC, gamedevshrimp commented on 04-lection2/01-histogram/index.html
> +                <p class="histogram__viewtext">View all</p>
поправил спасибо

2024-11-21 19:38 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-11-22 14:51 UTC, GSemikozov approved these changes

2024-11-22 14:51 UTC, merged